version: 1
status: invalid_for_model_evaluation
invalid_manifest: ../data/manifests/dataset-v1-invalid.json
path: ../data/SplitData
train: train/images
val: val/images
test: test/images

nc: 2
names: ["fake", "real"]
